spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect:  org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url:  jdbc:postgresql://localhost:5432/questionnaire
    username: questionnaire
    password: 123456
    driverClassName: org.postgresql.Driver
server:
  port: 8080
  contextPath:  /api
# JWT
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: "Bearer "
  route:
    authentication:
      path: auth
      refresh: "auth/refresh"
      register: "auth/register"